@startuml

title __SPACE-GAME's Class Diagram__\n

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.Calculator {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.ComputerPlayerView {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.Constants {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.DefaultModel {
    }
  }
  

  namespace org.heckcorp.domination {
    enum Direction {
    }
  }
  

  namespace org.heckcorp.domination {
    interface org.heckcorp.domination.GameModel {
    }
  }
  

  namespace org.heckcorp.domination {
    abstract class org.heckcorp.domination.GamePiece {
    }
  }
  

  namespace org.heckcorp.domination {
    interface org.heckcorp.domination.GameView {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.Hex {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.HexMap {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.LogFormatter {
    }
  }
  

  namespace org.heckcorp.domination {
    interface org.heckcorp.domination.ModelInitializer {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.NewGameInitializer {
    }
  }
  

  namespace org.heckcorp.domination {
    abstract class org.heckcorp.domination.Player {
    }
  }
  

  namespace org.heckcorp.domination {
    interface org.heckcorp.domination.Positionable {
    }
  }
  

  namespace org.heckcorp.domination {
    enum Status {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.Unit {
    }
  }
  

  namespace org.heckcorp.domination {
    interface org.heckcorp.domination.ViewMonitor {
    }
  }
  

  namespace org.heckcorp.domination {
    class org.heckcorp.domination.ViewMultiplexer {
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      class org.heckcorp.domination.desktop.ComputerPlayer {
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      class org.heckcorp.domination.desktop.Domination {
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      class org.heckcorp.domination.desktop.HumanPlayer {
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      class org.heckcorp.domination.desktop.NeutralPlayer {
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      class org.heckcorp.domination.desktop.Pathfinder {
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      class org.heckcorp.domination.desktop.TurnManager {
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.AnimatedImageIcon {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.Counter {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.HexDescriptionPanel {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.MapPane {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.MapView {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        interface org.heckcorp.domination.desktop.view.MapViewListener {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.MiniMap {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.ObservableState {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.SequentialExecutor {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.SwingView {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.UIResources {
        }
      }
    }
  }
  

  namespace org.heckcorp.domination {
    namespace desktop {
      namespace view {
        class org.heckcorp.domination.desktop.view.Util {
        }
      }
    }
  }
  

  org.heckcorp.domination.ComputerPlayerView .up.|> org.heckcorp.domination.GameView
  org.heckcorp.domination.ComputerPlayerView o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.ComputerPlayerView o-- org.heckcorp.domination.desktop.ComputerPlayer : player
  org.heckcorp.domination.DefaultModel .up.|> java.io.Serializable
  org.heckcorp.domination.DefaultModel .up.|> org.heckcorp.domination.GameModel
  org.heckcorp.domination.DefaultModel o-- org.heckcorp.domination.Player : currentPlayer
  org.heckcorp.domination.DefaultModel o-- org.heckcorp.domination.DefaultModel.GameStateManager : gameStateManager
  org.heckcorp.domination.DefaultModel o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.DefaultModel o-- org.heckcorp.domination.Unit : selectedUnit
  org.heckcorp.domination.DefaultModel o-- org.heckcorp.domination.desktop.TurnManager : turnManager
  org.heckcorp.domination.DefaultModel o-- org.heckcorp.domination.ViewMultiplexer : views
  org.heckcorp.domination.GamePiece .up.|> java.io.Serializable
  org.heckcorp.domination.GamePiece .up.|> org.heckcorp.domination.Positionable
  org.heckcorp.domination.GamePiece o-- org.heckcorp.domination.Hex : hex
  org.heckcorp.domination.GamePiece o-- org.heckcorp.domination.Player : owner
  org.heckcorp.domination.Hex .up.|> java.io.Serializable
  org.heckcorp.domination.Hex .up.|> org.heckcorp.domination.Positionable
  org.heckcorp.domination.Hex o-- org.heckcorp.domination.Player : owner
  org.heckcorp.domination.HexMap .up.|> java.io.Serializable
  org.heckcorp.domination.HexMap o-- org.heckcorp.domination.desktop.Pathfinder : pathfinder
  org.heckcorp.domination.LogFormatter -up-|> java.util.logging.Formatter
  org.heckcorp.domination.NewGameInitializer .up.|> org.heckcorp.domination.ModelInitializer
  org.heckcorp.domination.Player .up.|> java.io.Serializable
  org.heckcorp.domination.Player o-- org.heckcorp.domination.GameView : view
  org.heckcorp.domination.Player o-- org.heckcorp.domination.Unit : readyUnit
  org.heckcorp.domination.Unit .up.|> java.io.Serializable
  org.heckcorp.domination.Unit -up-|> org.heckcorp.domination.GamePiece
  org.heckcorp.domination.Unit o-- org.heckcorp.domination.Unit.Health : health
  org.heckcorp.domination.Unit o-- org.heckcorp.domination.Hex : lastHex
  org.heckcorp.domination.Unit o-- org.heckcorp.domination.Unit.Type : type
  org.heckcorp.domination.ViewMultiplexer .up.|> org.heckcorp.domination.GameView
  org.heckcorp.domination.desktop.ComputerPlayer -up-|> org.heckcorp.domination.Player
  org.heckcorp.domination.desktop.ComputerPlayer o-- org.heckcorp.domination.GameModel : model
  org.heckcorp.domination.desktop.ComputerPlayer o-- org.heckcorp.domination.ComputerPlayerView : myView
  org.heckcorp.domination.desktop.Domination .up.|> org.heckcorp.domination.ViewMonitor
  org.heckcorp.domination.desktop.Domination -up-|> javax.swing.JPanel
  org.heckcorp.domination.desktop.Domination o-- org.heckcorp.domination.desktop.view.SequentialExecutor : executor
  org.heckcorp.domination.desktop.Domination o-- org.heckcorp.domination.GameModel : model
  org.heckcorp.domination.desktop.Domination o-- org.heckcorp.domination.desktop.view.SwingView : view
  org.heckcorp.domination.desktop.HumanPlayer -up-|> org.heckcorp.domination.Player
  org.heckcorp.domination.desktop.NeutralPlayer -up-|> org.heckcorp.domination.Player
  org.heckcorp.domination.desktop.Pathfinder .up.|> java.io.Serializable
  org.heckcorp.domination.desktop.Pathfinder o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.desktop.TurnManager .up.|> java.io.Serializable
  org.heckcorp.domination.desktop.TurnManager .up.|> java.lang.Runnable
  org.heckcorp.domination.desktop.TurnManager o-- org.heckcorp.domination.DefaultModel : model
  org.heckcorp.domination.desktop.TurnManager o-- org.heckcorp.domination.Player : startPlayer
  org.heckcorp.domination.desktop.view.AnimatedImageIcon -up-|> javax.swing.ImageIcon
  org.heckcorp.domination.desktop.view.AnimatedImageIcon o-- org.heckcorp.domination.desktop.view.ObservableState : state
  org.heckcorp.domination.desktop.view.Counter -up-|> javax.swing.JLabel
  org.heckcorp.domination.desktop.view.Counter o-- org.heckcorp.domination.desktop.view.AnimatedImageIcon : icon
  org.heckcorp.domination.desktop.view.Counter o-- org.heckcorp.domination.desktop.view.ObservableState : state
  org.heckcorp.domination.desktop.view.HexDescriptionPanel -up-|> javax.swing.JPanel
  org.heckcorp.domination.desktop.view.HexDescriptionPanel o-- org.heckcorp.domination.desktop.view.SwingView.UIManager : uiManager
  org.heckcorp.domination.desktop.view.MapPane -up-|> javax.swing.JPanel
  org.heckcorp.domination.desktop.view.MapPane o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.desktop.view.MapPane o-- org.heckcorp.domination.desktop.view.UIResources : resources
  org.heckcorp.domination.desktop.view.MapView .up.|> java.awt.event.AdjustmentListener
  org.heckcorp.domination.desktop.view.MapView -up-|> javax.swing.JPanel
  org.heckcorp.domination.desktop.view.MapView o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.desktop.view.MapView o-- org.heckcorp.domination.desktop.view.MapPane : mapPane
  org.heckcorp.domination.desktop.view.MiniMap .up.|> org.heckcorp.domination.desktop.view.MapViewListener
  org.heckcorp.domination.desktop.view.MiniMap -up-|> javax.swing.JPanel
  org.heckcorp.domination.desktop.view.MiniMap o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.desktop.view.ObservableState -up-|> java.util.Observable
  org.heckcorp.domination.desktop.view.SequentialExecutor .up.|> java.lang.Runnable
  org.heckcorp.domination.desktop.view.SequentialExecutor .up.|> java.util.concurrent.Executor
  org.heckcorp.domination.desktop.view.SwingView .up.|> org.heckcorp.domination.GameView
  org.heckcorp.domination.desktop.view.SwingView -up-|> javax.swing.JPanel
  org.heckcorp.domination.desktop.view.SwingView o-- org.heckcorp.domination.desktop.view.SwingView.ViewDataManager : dataManager
  org.heckcorp.domination.desktop.view.SwingView o-- org.heckcorp.domination.desktop.view.SwingView.DisplayManager : displayManager
  org.heckcorp.domination.desktop.view.SwingView o-- org.heckcorp.domination.HexMap : map
  org.heckcorp.domination.desktop.view.SwingView o-- org.heckcorp.domination.ViewMonitor : monitor
  org.heckcorp.domination.desktop.view.SwingView o-- org.heckcorp.domination.desktop.view.UIResources : resources
  org.heckcorp.domination.desktop.view.SwingView o-- org.heckcorp.domination.desktop.view.SwingView.UIManager : uiManager
  org.heckcorp.domination.desktop.view.UIResources o-- org.heckcorp.domination.desktop.view.Counter : attackArrow
  org.heckcorp.domination.desktop.view.UIResources o-- org.heckcorp.domination.desktop.view.Counter : explosion
  org.heckcorp.domination.desktop.view.UIResources o-- org.heckcorp.domination.desktop.view.Counter : selection


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
