@startuml

title __SPACE-GAME's Class Diagram__\n

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.ComputerPlayer {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.ComputerPlayerView {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.Constants {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.DefaultModel {
    }
  }
  

  namespace org.heckcorp.spacegame {
    enum Direction {
    }
  }
  

  namespace org.heckcorp.spacegame {
    interface org.heckcorp.spacegame.GameModel {
    }
  }
  

  namespace org.heckcorp.spacegame {
    abstract class org.heckcorp.spacegame.GamePiece {
    }
  }
  

  namespace org.heckcorp.spacegame {
    interface org.heckcorp.spacegame.GameView {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.HumanPlayer {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.LogFormatter {
    }
  }
  

  namespace org.heckcorp.spacegame {
    interface org.heckcorp.spacegame.ModelInitializer {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.NeutralPlayer {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.NewGameInitializer {
    }
  }
  

  namespace org.heckcorp.spacegame {
    abstract class org.heckcorp.spacegame.Player {
    }
  }
  

  namespace org.heckcorp.spacegame {
    interface org.heckcorp.spacegame.Positionable {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.SequentialExecutor {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.SpaceGame {
    }
  }
  

  namespace org.heckcorp.spacegame {
    enum Status {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.TurnManager {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.Unit {
    }
  }
  

  namespace org.heckcorp.spacegame {
    class org.heckcorp.spacegame.ViewMultiplexer {
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      class org.heckcorp.spacegame.map.Calculator {
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      class org.heckcorp.spacegame.map.Hex {
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      class org.heckcorp.spacegame.map.HexMap {
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      class org.heckcorp.spacegame.map.Pathfinder {
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.AnimatedImageIcon {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.Counter {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.MapPane {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.MapView {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        interface org.heckcorp.spacegame.map.swing.MapViewListener {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.MiniMap {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        enum MovementAnimationState {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.UIResources {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        class org.heckcorp.spacegame.map.swing.Util {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace map {
      namespace swing {
        interface org.heckcorp.spacegame.map.swing.ViewMonitor {
        }
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace swing {
      class org.heckcorp.spacegame.swing.HexDescriptionPanel {
      }
    }
  }
  

  namespace org.heckcorp.spacegame {
    namespace swing {
      class org.heckcorp.spacegame.swing.SwingView {
      }
    }
  }
  

  org.heckcorp.spacegame.ComputerPlayer -up-|> org.heckcorp.spacegame.Player
  org.heckcorp.spacegame.ComputerPlayer o-- org.heckcorp.spacegame.GameModel : model
  org.heckcorp.spacegame.ComputerPlayer o-- org.heckcorp.spacegame.ComputerPlayerView : myView
  org.heckcorp.spacegame.ComputerPlayerView .up.|> org.heckcorp.spacegame.GameView
  org.heckcorp.spacegame.ComputerPlayerView o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.ComputerPlayerView o-- org.heckcorp.spacegame.ComputerPlayer : player
  org.heckcorp.spacegame.DefaultModel .up.|> java.io.Serializable
  org.heckcorp.spacegame.DefaultModel .up.|> org.heckcorp.spacegame.GameModel
  org.heckcorp.spacegame.DefaultModel o-- org.heckcorp.spacegame.Player : currentPlayer
  org.heckcorp.spacegame.DefaultModel o-- org.heckcorp.spacegame.DefaultModel.GameStateManager : gameStateManager
  org.heckcorp.spacegame.DefaultModel o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.DefaultModel o-- org.heckcorp.spacegame.Unit : selectedUnit
  org.heckcorp.spacegame.DefaultModel o-- org.heckcorp.spacegame.TurnManager : turnManager
  org.heckcorp.spacegame.DefaultModel o-- org.heckcorp.spacegame.ViewMultiplexer : views
  org.heckcorp.spacegame.GamePiece .up.|> java.io.Serializable
  org.heckcorp.spacegame.GamePiece .up.|> org.heckcorp.spacegame.Positionable
  org.heckcorp.spacegame.GamePiece o-- org.heckcorp.spacegame.map.Hex : hex
  org.heckcorp.spacegame.GamePiece o-- org.heckcorp.spacegame.Player : owner
  org.heckcorp.spacegame.HumanPlayer -up-|> org.heckcorp.spacegame.Player
  org.heckcorp.spacegame.LogFormatter -up-|> java.util.logging.Formatter
  org.heckcorp.spacegame.NeutralPlayer -up-|> org.heckcorp.spacegame.Player
  org.heckcorp.spacegame.NewGameInitializer .up.|> org.heckcorp.spacegame.ModelInitializer
  org.heckcorp.spacegame.Player .up.|> java.io.Serializable
  org.heckcorp.spacegame.Player o-- org.heckcorp.spacegame.GameView : view
  org.heckcorp.spacegame.Player o-- org.heckcorp.spacegame.Unit : readyUnit
  org.heckcorp.spacegame.SequentialExecutor .up.|> java.lang.Runnable
  org.heckcorp.spacegame.SequentialExecutor .up.|> java.util.concurrent.Executor
  org.heckcorp.spacegame.SpaceGame .up.|> org.heckcorp.spacegame.map.swing.ViewMonitor
  org.heckcorp.spacegame.SpaceGame -up-|> javax.swing.JPanel
  org.heckcorp.spacegame.SpaceGame o-- org.heckcorp.spacegame.SequentialExecutor : executor
  org.heckcorp.spacegame.SpaceGame o-- org.heckcorp.spacegame.GameModel : model
  org.heckcorp.spacegame.SpaceGame o-- org.heckcorp.spacegame.swing.SwingView : view
  org.heckcorp.spacegame.TurnManager .up.|> java.io.Serializable
  org.heckcorp.spacegame.TurnManager .up.|> java.lang.Runnable
  org.heckcorp.spacegame.TurnManager o-- org.heckcorp.spacegame.DefaultModel : model
  org.heckcorp.spacegame.TurnManager o-- org.heckcorp.spacegame.Player : startPlayer
  org.heckcorp.spacegame.Unit .up.|> java.io.Serializable
  org.heckcorp.spacegame.Unit -up-|> org.heckcorp.spacegame.GamePiece
  org.heckcorp.spacegame.Unit o-- org.heckcorp.spacegame.Unit.Health : health
  org.heckcorp.spacegame.Unit o-- org.heckcorp.spacegame.map.Hex : lastHex
  org.heckcorp.spacegame.Unit o-- org.heckcorp.spacegame.Unit.Type : type
  org.heckcorp.spacegame.ViewMultiplexer .up.|> org.heckcorp.spacegame.GameView
  org.heckcorp.spacegame.map.Hex .up.|> java.io.Serializable
  org.heckcorp.spacegame.map.Hex .up.|> org.heckcorp.spacegame.Positionable
  org.heckcorp.spacegame.map.Hex o-- org.heckcorp.spacegame.Player : owner
  org.heckcorp.spacegame.map.HexMap .up.|> java.io.Serializable
  org.heckcorp.spacegame.map.HexMap o-- org.heckcorp.spacegame.map.Pathfinder : pathfinder
  org.heckcorp.spacegame.map.Pathfinder .up.|> java.io.Serializable
  org.heckcorp.spacegame.map.Pathfinder o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.map.swing.AnimatedImageIcon -up-|> javax.swing.ImageIcon
  org.heckcorp.spacegame.map.swing.Counter -up-|> javax.swing.JLabel
  org.heckcorp.spacegame.map.swing.Counter o-- org.heckcorp.spacegame.map.swing.AnimatedImageIcon : icon
  org.heckcorp.spacegame.map.swing.MapPane -up-|> javax.swing.JPanel
  org.heckcorp.spacegame.map.swing.MapPane o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.map.swing.MapPane o-- org.heckcorp.spacegame.map.swing.UIResources : resources
  org.heckcorp.spacegame.map.swing.MapView .up.|> java.awt.event.AdjustmentListener
  org.heckcorp.spacegame.map.swing.MapView -up-|> javax.swing.JPanel
  org.heckcorp.spacegame.map.swing.MapView o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.map.swing.MapView o-- org.heckcorp.spacegame.map.swing.MapPane : mapPane
  org.heckcorp.spacegame.map.swing.MiniMap .up.|> org.heckcorp.spacegame.map.swing.MapViewListener
  org.heckcorp.spacegame.map.swing.MiniMap -up-|> javax.swing.JPanel
  org.heckcorp.spacegame.map.swing.MiniMap o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.map.swing.UIResources o-- org.heckcorp.spacegame.map.swing.Counter : attackArrow
  org.heckcorp.spacegame.map.swing.UIResources o-- org.heckcorp.spacegame.map.swing.Counter : explosion
  org.heckcorp.spacegame.map.swing.UIResources o-- org.heckcorp.spacegame.map.swing.Counter : selection
  org.heckcorp.spacegame.swing.HexDescriptionPanel -up-|> javax.swing.JPanel
  org.heckcorp.spacegame.swing.HexDescriptionPanel o-- org.heckcorp.spacegame.swing.SwingView.UIManager : uiManager
  org.heckcorp.spacegame.swing.SwingView .up.|> org.heckcorp.spacegame.GameView
  org.heckcorp.spacegame.swing.SwingView -up-|> javax.swing.JPanel
  org.heckcorp.spacegame.swing.SwingView o-- org.heckcorp.spacegame.swing.SwingView.ViewDataManager : dataManager
  org.heckcorp.spacegame.swing.SwingView o-- org.heckcorp.spacegame.swing.SwingView.DisplayManager : displayManager
  org.heckcorp.spacegame.swing.SwingView o-- org.heckcorp.spacegame.map.HexMap : map
  org.heckcorp.spacegame.swing.SwingView o-- org.heckcorp.spacegame.map.swing.ViewMonitor : monitor
  org.heckcorp.spacegame.swing.SwingView o-- org.heckcorp.spacegame.map.swing.UIResources : resources
  org.heckcorp.spacegame.swing.SwingView o-- org.heckcorp.spacegame.swing.SwingView.UIManager : uiManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
